#!/bin/bash
echo "# GrpcTutorial" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:manmedia/GrpcTutorial.git
git push -u origin mainø

